# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 75ba5f0ff98c90221f0798f4289c2fb79e03632bbcf5dd952cf999cba36cdc04dbffe395449efbc0556aac3664a2c5ff49e029ff3b2928b7121c6dfe7260f832

test:
  secret_key_base: 75e025a541957d87cd973c59d4be66a4bee509251efbeee994e9851c1be92a6c5832d7fd9513a8a469fd61a9cc63050a59cb1a69c4dfbe417b8f41eaaa5e6e19

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
